// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AddressAutocompleteScript(placesApiKey string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if placesApiKey != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<script>\n\t\t\tfunction initAddressAutocomplete() {\n\t\t\t\t[\"riding-address-input\", \"nav-address-input\", \"profile-address-input\"].forEach(function(id) {\n\t\t\t\t\tvar input = document.getElementById(id);\n\t\t\t\t\tif (!input) {\n\t\t\t\t\t\treturn;\n\t\t\t\t\t}\n\t\t\t\t\tvar autocomplete = new google.maps.places.Autocomplete(input, {\n\t\t\t\t\t\tcomponentRestrictions: { country: \"ca\" },\n\t\t\t\t\t\ttypes: [\"geocode\"],\n\t\t\t\t\t\tfields: [\"formatted_address\"],\n\t\t\t\t\t});\n\t\t\t\t\tautocomplete.addListener(\"place_changed\", function() {\n\t\t\t\t\t\tvar place = autocomplete.getPlace();\n\t\t\t\t\t\tif (place && place.formatted_address) {\n\t\t\t\t\t\t\tinput.value = place.formatted_address;\n\t\t\t\t\t\t}\n\t\t\t\t\t});\n\t\t\t\t});\n\t\t\t}\n\t\t</script> <script id=\"places-api-loader\" data-places-key=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(placesApiKey)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/templates/address_autocomplete.templ`, Line: 26, Col: 63}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"></script> <script>\n\t\t\t(function() {\n\t\t\t\tvar loader = document.getElementById(\"places-api-loader\");\n\t\t\t\tvar key = loader ? loader.dataset.placesKey : \"\";\n\t\t\t\tif (!key) {\n\t\t\t\t\treturn;\n\t\t\t\t}\n\t\t\t\tvar script = document.createElement(\"script\");\n\t\t\t\tscript.src = \"https://maps.googleapis.com/maps/api/js?key=\" + encodeURIComponent(key) + \"&libraries=places&callback=initAddressAutocomplete&loading=async\";\n\t\t\t\tscript.async = true;\n\t\t\t\tscript.defer = true;\n\t\t\t\tdocument.head.appendChild(script);\n\t\t\t})();\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
